### ISSUE TITLE
Song of Solomon fails regex

### ISSUE THREAD

**Issue by tayknight** [jonathanvanschenck/biblescrapeway#2]
match = cls.BCV_regex.match(_string)

fails for Song of Solomon with regex 
`^([0-9]?[ _\\.]?[A-Za-z]+)[\\._ ]*([0-9]+)[\\.: _]?([0-9]*)$`

I think this is the only book that fails.

**Comment by jonathanvanschenck** [comment]
Fixed with commit 95333ea6b41ed2fc8a46c9b7a2135173fb78937d and version 0.2.1 (actually 0.2.0 it the tag for the commit, but relative imports are the worst, so the actual pip-installable version is 0.2.1)

**Comment by jonathanvanschenck** [comment]
I also modified the cli to version printing support, which forced me to rebrand the '-v/--version' to '-t/--translation' in 0.3.0
