### ISSUE TITLE
I dont this this code scraps formatted text

### ISSUE THREAD

**Issue by RayReddingtonx** [jonathanvanschenck/biblescrapeway#4]
It is ignoring the italics or formatted text in the verse text from the bible versions. You can verify this by scraping Romans 10:6 NTE or the bold text in NET

**Comment by jonathanvanschenck** [comment]
The original intent of the tools was to target cli usage, where pure ASCII output is preferred. Though, adding additional output formats which can support html/markdown formatting should totally be doable and within scope. What kind of formatted output are you looking for?

**Comment by RayReddingtonx** [comment]
I dont know anything about coding. I just happen to do it all using the ai chatbots help using python for the first time. It gave me to use  find_all and "tags" and "Verse" attributes to include the formatted html text, but the result error showed that this package doesn't have those. Then it suggested to use beautifulsoup, but soup does not generate the bible verse text the way we want and its also very bad for this purpose. I guess you need to edit the package to include html or find_all attributes to include bold and italic texts.
